### PR TITLE
Implemented dynamic update

### PR DESCRIPTION
**Pull request by Cellule**
Closes https://github.com/fmoo/react-typeahead/issues/11
Duplicate of #15

### CODE REVIEW

**Comment by fmoo** [comment]
Is this PR good to go?  Can you add any unittests to verify this behavior?

**Comment by TryingToImprove** [comment]
I do not understand why you want to set the `defaultValue` when the options changes.

When you are using the Typeahead with AJAX, do you then want to update the `defaultValue` on `<Typeahead />` as the value of the `input` dom?

**Comment by derekdowling** [comment]
:wave: hey, can you guys finish this off. This is the only good typeahead currently and having this feature would be swell.

**Comment by fmoo** [comment]
acf88f477e130817f4b8b496239a4d14d1a24e98 should work for this.   @derekdowling can you verify?

**Pull request closed without merging**
