### PR TITLE
remove selectedTokens from change callbacks

### PR DESCRIPTION
**Pull request by growlsworth**
as requested in https://github.com/fmoo/react-typeahead/pull/79

### CODE REVIEW

**Comment by growlsworth** [comment]
Hey @fmoo, is this a direction you're still interested in? I'd personally prefer to keep selectedTokens in the callback, but could be swayed, especially if there's an [exposed component function](https://facebook.github.io/react/tips/expose-component-functions.html) to get the selected tokens.

**Comment by fmoo** [comment]
Yeah, an exposed component function makes a lot more sense before pulling this in.

I was also hoping to get a couple of bugfixes into 1.0.x before merging this and bumping to 1.1.x, but haven't had the time.

**Comment by growlsworth** [comment]
Hey @fmoo, I appreciate the response.

The main reason I ask is purely selfish. I'm running off of this branch in prod because of this expected breaking change. `npm outdated` can't show if I'm outdated or not because it's running off a git sha. And I just prefer to be running off published versions. Let me know if I can help.

**Comment by fmoo** [comment]
@growlsworth - If you add the component function to this PR, I'll merge this in sooner than later.  It seems super useful.

Thanks for your patience.

**Comment by growlsworth** [comment]
Cool, should be an easy update. I can't work on it today, might have time this weekend.

**Comment by growlsworth** [comment]
Added the exposed component function, documentation, and basic test. Let me know if you'd like for it to return a clone of the object instead of the object itself.

**Pull request merged**
