### PR TITLE
Add onChange, onKeyUp, onFocus, and onBlur event to Typeahead

### PR DESCRIPTION
**Pull request by ahlee2326**

### CODE REVIEW

**Comment by fmoo** [comment]
can you rebase/merge with master?  I merged another PR and it seems to have created a conflict.

**Comment by fmoo** [comment]
Ok, so just out of curiosity, did you have any specific use-cases for all of these?

I've actually been looking to try provide a simplified set of events/callbacks, such as deprecating onKeyDown in favor of onChange, and implicitly invoking onChange on the entry state changes in realtime.  Thoughts?

**Comment by ahlee2326** [comment]
In my case, I am using onKeyUp to invokes the search function and onChange to updates other state variables. And I think it's important to remain all the common events as Typeahead should be only a wrapper of normal input field with the capability of doing autocomplete.

**Comment by claydiffrient** [comment]
Any update on this @fmoo ?  I'm trying to load data via async and as part of that I need to be able to determine what the user has typed in. I'm currently hooking into the `onKeyDown` event, but because doing `event.target.value` at that point returns the value without the latest keypress in place.  It would be nice to have `onChange` or `onKeyUp` to be able to get a more accurate indication of what the user has typed so that my async search can be improved.

**Comment by fmoo** [comment]
Hi @claydiffrient

I just merged this and did a 1.0.6 release if you need this in prod.

**Comment by claydiffrient** [comment]
Sweet @fmoo! Thanks so much!

**Comment by xizhao** [comment]
onChange should receive the old and new values of the input along with the synthetic event imo

**Pull request merged**
