### PR TITLE
added onKeyDown and onKeyUp to the Tokenizer component

### PR DESCRIPTION
**Pull request by growlsworth**
I have a use case where I need to create tokens on the fly when a token isn't found in the dropdown. 

Thanks.

### CODE REVIEW

**Comment by fmoo** [comment]
I pulled in #90 just now, can you resolve the conflicts and I'll merge this in.

**Comment by growlsworth** [comment]
Thanks. fixed.

**Comment by growlsworth** [comment]
not fixed. I'm an idiot.

**Comment by growlsworth** [comment]
ok fixed fo reals.

**Pull request merged**
