### PR TITLE
Added ability to change <input> to <textarea> from a boolean flag

### PR DESCRIPTION
**Pull request by OtaK**
Hello,

As I said before, I needed this kind of simple functionality.

I know it is kinda a duplicate with #34, but the aim is much simpler, implications are much smaller, and it would fit 90% of usages for this.

Unit tests are included also, and are all passing.

### CODE REVIEW

**Comment by OtaK** [comment]
@fmoo What feedback do you want?

**Comment by fmoo** [comment]
Just curious what other folks following the project think of this change, will it break them or their plans, etc.

**Comment by OtaK** [comment]
@fmoo Nothing breaks there, it's just a completely optional prop that allows a bit more flexibility. And I don't mind it being removed when #34 gets merged in as they serve the same purpose (though my PR is in a much more limited scope).
You can check the unit tests anyway, there's no breaking change.

**Comment by fmoo** [comment]
Can you add a description of the feature to README.md ?

**Comment by OtaK** [comment]
@fmoo Done! Feel free to ask for anything else.

Have a great day!

**Pull request merged**
