### PR TITLE
Custom options

### PR DESCRIPTION
**Pull request by georgwiese**
I needed to extend the typeahead to be able to provide custom options (arbitrary options rather than strings) together with `getSearchString()` and `getDisplayString` functions.

I made sure to not break downward compatibility, wrote tests, added an example and updated the documentation. Maybe others will also find this feature useful :)

Beware that it includes [this pull request](https://github.com/fmoo/react-typeahead/pull/33) which is not yet merged, since I was branching from it.

### CODE REVIEW

**Comment by fmoo** [comment]
Any chance you could rebase -i origin/master and either merge some of these commits together or remove the unrelated ones (and submit those separately)?

It's harder to review when there's so much incremental / unrelated work.

**Comment by georgwiese** [comment]
@fmoo The changes of the other pull request are already reflected in your current master, so there is only one feature added in this PR. I just merged your current master into this branch.

**Comment by fmoo** [comment]
I really like this diff and I think it really brings this component to the next level.

That said, I think if we build on this change, we can almost resolve several issues (#40, #42), as well as take care of a couple of outstanding PRs (#30, #24)

Some feedback so far / questions I'd like your thoughts on before I proceed:

- If `name` is set, the hidden `<input>`'s value gets set to `[Object object]`.  The proposed API below might help with this, but there might be an easier fix I'm not thinking of.
- The new methods are only set on Typeahead, but not Tokenizer as well.
- Since the props will be common to both, having a mixin to help avoid redundancy might make things cleaner
- Does `getDisplayString` need to return a string?  Or can it return jsx/html?  if the latter, a name like `renderOption` might be more appropriate.
- I was thinking of changing the names as follows:
 - `getSearchString` --> `getOptionSearchString`
 - `getDisplayString` --> `renderOption`
 - new `getOptionValue` (to accommodate the `name=` props' generated inputs?)
- I haven't tested yet, but can we add support for "options as objects" by changing the default callbacks for `getOptionSearchString`, `renderOption`, `getOptionValue`, etc in a backwards compatible way like this?:

 ```javascript
  getOptionSearchString: function(option) { return option.search || option },
  getOptionValue: function(option) { return option.display || option },
  renderOption: function(option) { return option.render || option }
```

Let me know your thoughts on this.

**Comment by thehuey** [comment]
:+1: Would love to see this as well.

**Comment by growlsworth** [comment]
+1

**Pull request merged**
