### PR TITLE
Allow passing custom props to the <input> to e.g. disallow autocorrect.

### PR DESCRIPTION
**Pull request by seansfkelley**
I'm using react-typeahead on iOS and I want to be able to turn off autocorrect/autocapitalize, etc. (especially since fuzzy matching usually has users putting in inputs that are not actually words).

### CODE REVIEW

**Comment by seansfkelley** [comment]
I just realized you could roll `placeholder` and `defaultValue` into this. I didn't do it cause it's a little opaque, though I suppose you could call it out in the docs. Thoughts?

**Comment by fmoo** [comment]
Hey, I merged #60 first which seems to have created a conflict.  And you update the to resolve?

**Comment by seansfkelley** [comment]
Done!

**Comment by fmoo** [comment]
I'm really on the fence about whether these should be individual attributes vs. attributes on object like this.

Advantages to individual attributes is that we can provide better validation via propTypes (e.g., React.PropTypes.oneOf(["none", "sentences", "word"]) and documentation, but I'd prefer the opaque object for random attributes that are not part of the spec.

Anyone else want to weigh in on this?

**Comment by seansfkelley** [comment]
I totally stole this from [react-select](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L37) (which I was using before this library) and I found it immensely useful. FWIW here's the original PR: https://github.com/JedWatson/react-select/pull/82 not that there's much discussion.

**Comment by franleplant** [comment]
This is super useful! Nice

**Pull request merged**
