### PR TITLE
Add support for user entered values to typeahead and tokenizer.

### PR DESCRIPTION
**Pull request by thehuey**
A common typeahead UI allows users to enter non-supplied options.  This pull request adds the functionality by allowing a new property: allowCustomValues={#characters}.  The default is false which disables custom values.  By supplying the minimum number of characters, user input which does not match a valid option and exceeds the minimum characters is prepended to the options list, allowing the user to select it as normal.

### CODE REVIEW

**Comment by fmoo** [comment]
I for sure like this feature, but I need to think about the implementation a little bit more.

**Comment by thehuey** [comment]
How do I test for function is called?  I checked and it looks like onTokenAdd does get called for a custom value.  onOptionSelected also gets called for Typeahead.

I want to add it as a test, but I can't figure out how to do something like assert(this.component.props.onOptionSelected.isCalled())

**Comment by fmoo** [comment]
>  How do I test for function is called?

You could set a custom callback that sets a variable or bring in a chai plugin that implements mocking/doubles/spies.

Some examples:
- chai-spies (http://chaijs.com/plugins/chai-spies)
- jack-chai (https://github.com/jackjs/jack-chai#invoke)
- sinon-chai (http://chaijs.com/plugins/sinon-chai)

**Comment by thehuey** [comment]
Sweet, yeah I found sinon and am trying to hook it up in the tests.

**Comment by thehuey** [comment]
Alright, I've added spies to the test.  Verified for both Typeahead and Tokenizer.  Let me know if it's good to go.

**Comment by wookiehangover** [comment]
:+1: looks good to me

**Pull request merged**
