### PR TITLE
Added gulp build task for webpack support

### PR DESCRIPTION
**Pull request by vegetableman**
Fixes issue #14 #39
It follows the convention of https://github.com/zippyui/react-date-picker for easier npm sharing. Updated package.json as well.

Note:- the change in dist/react-typeahead.js is due to the build task.

### CODE REVIEW

**Comment by vegetableman** [comment]
Ran in to this issue. Would be great to see it supported. Do let me know if any changes/cleanups required.

**Comment by fmoo** [comment]
Let's do it!

**Comment by vegetableman** [comment]
That was an unintended push in order to test it's compatibility with the latest react version used on my local project, since, having two different versions of the same lib are considered two separate libs by package bundlers like webpack.

**Comment by fmoo** [comment]
Gotcha.  Well, if nothing broke, we'll keep it.

Let me know

On Sat, Apr 4, 2015 at 8:05 AM, Vignesh Anand <notifications@github.com>
wrote:

> That was an unintended push in order to test it's compatibility with the
> latest react version used on my local project, since, having two different
> versions of the same lib are considered two separate libs by package
> bundlers like webpack.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fmoo/react-typeahead/pull/49#issuecomment-89592242>.
>



-- 
Peter Ruibal

**Comment by fmoo** [comment]
Random thought: do we need to actually check-in the contents of lib/ ?  Or do they just need to be part of the package when it's published?

What I mean is, would it be safe remove the files in lib/, and add lib/ to .gitignore, but not .npmignore?

It can be confusing for contributors if they're making changes to lib/ instead of src/

**Comment by vegetableman** [comment]
Makes sense. Checkout PR #51.

**Comment by thehuey** [comment]
not sure how .npmignore will fix dependency references in the form of 

'react-typeahead' : 'https://github.com/fmoo/react-typeahead'

The lib/ directory being referenced is no longer part of the GIT repo.

What's the impetus for removing lib/?  Save space in the repo? Reduce conflicts?

**Comment by vegetableman** [comment]
@thehuey To reduce confusion. Check line:-
> It can be confusing for contributors if they're making changes to lib/ instead of src/

**Comment by thehuey** [comment]
Hmm... if that is the only reason, I would vote to put it back in.

src/ is a pretty standard practice.  Adding an entry in the README.md file
under Developing should clear up any confusions.

**Comment by fmoo** [comment]
So I just pushed the empty .npmignore, and as a result, was able to build a correct 1.0.2 release (which I subsequently published to npm).

dependencies installed from local/development checkouts should also work correctly.

Unfortunately, per npm/npm#3055, `npm prepublish` is not run for dependencies fetched directly from git, and this use case is broken by the current model.

I'd really prefer to avoid checking in build artifacts to the source repository, but if this is breaking a log of folks, I can be convinced.  Otherwise, we can just be more aggressive about doing minor and patch releases for new features.

**Pull request merged**
