### PR TITLE
removed unnecessary getDOMNode() calls in code

### PR DESCRIPTION
**Pull request by growlsworth**
access element directly
reference: https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html

> NOTE: I did not remove all `findDOMNode()` calls in the test suite. I removed the ones that were unnecessary.

### CODE REVIEW

**Comment by growlsworth** [comment]
Oh and this also forces a require of react 14.

**Comment by dminkovsky** [comment]
This is what I did locally as a stop-gap measure.

**Comment by mathieumg** [comment]
> Oh and this also forces a require of react 14.

Shouldn't it have been tagged as 2.0.0 instead of 1.1.5 then?

**Comment by fmoo** [comment]
At a minimum, it should have been 1.2.0.

Did you want a revert as 1.1.6, and to push this out into 1.2?

On Fri, Oct 30, 2015 at 12:02 PM, Mathieu M-Gosselin <
notifications@github.com> wrote:

> Oh and this also forces a require of react 14.
>
> Shouldn't it have been tagged as 2.0.0 instead of 1.1.5 then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fmoo/react-typeahead/pull/136#issuecomment-152618735>.
>



-- 
Peter Ruibal

**Comment by mathieumg** [comment]
Technically I thought it shouldn't be anything below 2.0 since it is breaking, however it's not breaking by itself, its peer dependency (React here) is correctly set to minimally be `>= 0.14`, so I imagine 1.2 would be fine, but it certainly should be more than just a patch. :stuck_out_tongue: 

No need to revert on GitHub, just unpublishing 1.1.5 and republishing as 1.2.0 would be fine.

**Pull request merged**
