### PR TITLE
Added lib to .gitignore and added prepublish script

### PR DESCRIPTION
**Pull request by vegetableman**

### CODE REVIEW

**Comment by fmoo** [comment]
Thanks so much!  I've been wanting to get this working with webpack for some time.

**Comment by FoxxMD** [comment]
:+1: This is awesome! Except that it breaks using forks with npm (for me). Since the `lib` folder is now ignored any projects that depend on the forks have to either remove it from `gitignore` (and commit it) or manually copy in a built `lib` folder in to the module folder in `node_modules` in their project.

Not the biggest deal but is there an easy fix for this?

**Comment by fmoo** [comment]
@FoxxMD - can you try adding an empty .gitignore to the repository root and let me know if that helps?

**Comment by fmoo** [comment]
@FoxxMD - can you try adding an empty .npmignore to the repository root and let me know if that helps?

**Pull request merged**
