### PR TITLE
Replace TypeaheadSelector with custom Component

### PR DESCRIPTION
**Pull request by lPadier**
This allows more customisation of the results and also simplifies the creation of a empty results message inside the customListComponent.

### CODE REVIEW

**Comment by jsergiu** [comment]
Hi Peter,

Please review / approve this feature. I need to display some custom options and I think this changes can help. It would be nice to be able to return a dom object from displayOption()

**Comment by fmoo** [comment]
I was planning to take a look this weekend. 

This week has been crazy busy and I got what feels like 10 PRs on Monday. :)

**Comment by fmoo** [comment]
@lPadier - any chance you can update the README.md with the new method definition?

**Comment by lPadier** [comment]
There is one thing that has slightly changed for people that do not use the customListComponent.

In order to take into account the no result use case, the no results case now renders an empty `ul` instead of an empty `span`.

**Comment by lPadier** [comment]
@fmoo - any updates on the status of this pull request ?

**Comment by fmoo** [comment]
manually resolved the merge conflicts.  Will be pushing a 1.1.2 release shortly.

**Pull request merged**
