### PR TITLE
a value should be selected if defaultValue is provided on initialization

### PR DESCRIPTION
**Pull request by janx**
So the dropdown list will not show at first.

### CODE REVIEW

**Comment by fmoo** [comment]
From some previous discussions, I think the desired behavior is for this to be a separate option.  `defaultValue` is meant to be the default value of the text entry, but if an option has been *selected* 

What are your thoughts on the following two options to move forward with this:

1) Implement the original behavior with the `defaultEntryValue` prop, keeping your existing functionality as `defaultValue`.
2) Restore the original behavior as `defaultValue`, and implement this new (arguably more desirable) functionality as  `defaultSelection`.

**Comment by janx** [comment]
Thanks for the background. Option 2 looks better to me too.

Is `value` a possible alternative name? In my scenario I use the typeahead input in an EDIT form, which will be inflated by existing values, so what I need is not a `defaultSelection`, but to specify the value of input, and the input renders the value, just like the value of a text input.

**Comment by fmoo** [comment]
value sounds good.

**Comment by janx** [comment]
Great! I'll just close this PR.

**Comment by fmoo** [comment]
@janx - will yoube submitting an alternate PR?

**Comment by janx** [comment]
@fmoo created https://github.com/fmoo/react-typeahead/pull/102

**Pull request closed without merging**
