### PR TITLE
Objects as data

### PR DESCRIPTION
**Pull request by TryingToImprove**
It should be possible to pass a array of objects instead of strings, and the onOptionSelected should give the object instead of the option-term.

**WARNING**  the "Add key on the option"-commit might conflict with [this pull request](https://github.com/fmoo/react-typeahead/pull/28)

### CODE REVIEW

**Comment by darkyen** [comment]
+1

**Comment by raysuelzer** [comment]
+1

**Comment by yujinlim** [comment]
+1

**Comment by krvital** [comment]
+1

**Comment by jerryf196** [comment]
+1

**Comment by growlsworth** [comment]
+1

**Comment by fmoo** [comment]
Closed in favor of #61

**Pull request closed without merging**
